# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Hildreth is a Toronto Based Designer.
email: daniel.john.hildreth@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I enjoy working within all mediums of design; from desktop websites
  to branding and editorial pieces. I’d love to hear from you and
  discuss your next project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://danielhildreth.com" # the base hostname & protocol for your site
permalink: /journal/:title
timezone: America/Toronto
fb_admins: https://www.facebook.com/dan.hildreth
exclude: [README.md]

# Build settings
markdown: kramdown
host: 0.0.0.0
port: 4000

# SASS settings
sass:
  sass_dir: _sass
  style: compressed

# Collection settings
collections:
  work:
    output: true
    permalink: /work/:title

# Defaults settings
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post" # overrides previous default layout
      body_class: "post"
      author: "Daniel Hildreth"
